name: Autobuild

on:
  push:
    branches: '*'
    tags-ignore: '*'
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash

jobs:
  generate-ci-config:
    name: Generate CI Configuration
    uses: './.github/workflows/ci-config.yml'

  Autobuild:
    needs: [generate-ci-config]
    uses: './.github/workflows/build.yml'
    with:
      matrix: ${{ needs.generate-ci-config.outputs.matrix }}
